from .Abstract import abstract_df
from .AdminStrand import admin_strand_df, adminstrand_df
from .eppi_ID import eppiid_df
from .Age import student_age, student_age_df
from .Attrition import attrition_df
from .Author import author_df
from .Baseline_Differences import baseline_differences_df
from .CIlowerSMD import cilowersmd_df
from .CIupperSMD import ciuppersmd_df
from .Clustering import clustering_df
from .Comparability_Variables_Reported import comparability_vars_reported_df
from .Comparability import comparability_df
from .Country import country_df
from .CurriculumSubject import curriculum_subject_df
from .Date import year_df
from .DOI import doi_df
from .Editors import editedby_df
from .EducationalSetting import edusetting_df
from .EducationalSetting import educational_setting_df
from .EffectSizeType import effectsizetype_df
from .eppi_ID import eppiid_df
from .Gender import gender_df
from .GenderSplit import gender_split_df
from .Group1_Mean import group1mean_df
from .Group1_N import group1N_df
from .Group1_SD import group1sd_df
from .Group2_Mean import group2mean_df
from .Group2_N import group2N_df
from .Group2_SD import group2sd_df
from .Institution import institution_df
from .InterventionCostsReported import intervention_costs_df
from .InterventionDelivery import intervention_delivery_df
from .InterventionDelivery import interventiondelivery_df
from .InterventionDescription import intervention_description_df
from .InterventionDetail import intervention_detail_df
from .InterventionDuration import InterventionDuration_Comments_df
from .InterventionDuration import intervention_duration_df
from .InterventionEvaluation import intervention_evaluation_df
from .InterventionFocus import intervention_focus_df
from .InterventionFrequency import intervention_frequency_df
from .InterventionFrequency import InterventionFrequency_Comments_df
from .InterventionInclusion import intervention_inclusion_df
from .InterventionInclusion import DigitalTechnology_df
from .InterventionInclusion import Parents_or_Community_Volunteers_df
from .InterventionName import intervention_name_df
from .InterventionObjectives import intervention_objectives_df
from .InterventionOrganizationType import InterventionOrgType_df
from .InterventionOrganizationType import intervention_org_type
from .InterventionSessionLength import intervention_session_length_df
from .InterventionSessionLength import InterventionSessionLength_Comments_df
from .InterventionTeachingApproach import intervention_teaching_approach_df
from .InterventionTeachingApproach import InterventionTeachingApproach_df
from .InterventionTime import intervention_time_df
from .InterventionTime import InterventionTime_df
from .InterventionTrainingProvided import intervention_training_provided_df
from .InterventionTrainingProvided import InterventionTrainingProvided_df
from .Issue import issue_df
from .LevelofAssignment import level_of_assignment_df
from .NumberofClasses import number_of_classes_df
from .NumberofClasses import number_of_classes_total_Comments_df
from .NumberofSchools import number_of_schools_df
from .NumberofSchools import number_of_schools_total_Comments_df
from .Other_Outcomes import other_outcomes_df
from .Outcome import outcome_df
from .OutcomeComparison import out_comp_df
from .OutcomeDescription import outcome_description_df
from .OutcomeID import outcome_ID_df
from .OutcomeMeasure import outcome_measure_df
from .Outcome_TestType import testtype_df
from .OutcomeText import outcome_text_df
from .OutcomeTitle import outcome_title_df
from .OutcomeType import outcometype_df
from .Pages import pages_df
from .Parent_Authors import parentauthors_df
from .ParentTitle import parentittle_df
from .ParticipantAssignment import participant_assignment_df
from .PrimaryOutcomeDescStatsControlGroup_TWO import DescStatsPrimaryOutcomeReported_Control_TWO_df
from .PrimaryOutcomeDescStatsControlGroup import DescStatsPrimaryOutcomeReported_Control_df
from .PrimaryOutcomeDescStatsInterventionGroup_TWO import DescStatsPrimaryOutcomeReported_Intervention_TWO_df
from .PrimaryOutcomeDescStatsInterventionGroup import DescStatsPrimaryOutcomeReported_Intervention_df
from .PrimaryOutcomeDescStatsReported import DescStatsOutcomeReported_df
from .PublicationType_EPPI import pubtype_eppi_df
from .PublicationType import publication_type_df, publicationtype_df
from .Publisher import publisher_df
from .Randomisation import randomisation_df
from .Sample_Size_Analyzed import analyzed_sample_size_df
from .Sample_Size_Initial import initial_sample_size_df
from .Sample import sample_df
from .SampleSize import sample_size_df
from .SampleSize import sample_size_Comments_df
from .ses_fsm import ses_fsm_df
from .ses_fsm import low_ses_percentage_Comments_df
from .sesmd import sesmd_df
from .ShortTitle import shorttitle_df
from .smd import smd_df
from .Source import source_df
from .Study_place import study_place_df
from .StudyDesign import study_design_df
from .StudyDesign import studydesign_df
from .StudyRealism import study_realism_df
from .TestType import testtype_outcome_df
from .Title import title_df
from .ToolkitStrand import toolkitstrand_df
from .TreatmentGroup import treatment_group_df
from .TypeName import typename_df
from .URL import url_df
from .Volume import volume_df